// Список документов. Меняйте title (название) и file (имя файла в папке documents).
// Чтобы добавить документ — добавьте строку; расширение может быть любым (.pdf, .docx, .xlsx).
const DOCS = [
  { n: 1, title: "Документ 1", file: "documents/1.pdf" },
  { n: 2, title: "Документ 2", file: "documents/2.pdf" },
  { n: 3, title: "Документ 3", file: "documents/3.pdf" },
  { n: 4, title: "Документ 4", file: "documents/4.pdf" },
  { n: 5, title: "Документ 5", file: "documents/5.pdf" },
  { n: 6, title: "Документ 6", file: "documents/6.pdf" },
  { n: 7, title: "Документ 7", file: "documents/7.pdf" },
  { n: 8, title: "Документ 8", file: "documents/8.pdf" },
  { n: 9, title: "Документ 9", file: "documents/9.pdf" },
  { n: 10, title: "Документ 10", file: "documents/10.pdf" },
  { n: 11, title: "Документ 11", file: "documents/11.pdf" },
  { n: 12, title: "Документ 12", file: "documents/12.pdf" },
  { n: 13, title: "Документ 13", file: "documents/13.pdf" },
  { n: 14, title: "Документ 14", file: "documents/14.pdf" },
  { n: 15, title: "Документ 15", file: "documents/15.pdf" },
  { n: 16, title: "Документ 16", file: "documents/16.pdf" },
  { n: 17, title: "Документ 17", file: "documents/17.pdf" },
  { n: 18, title: "Документ 18", file: "documents/18.pdf" },
  { n: 19, title: "Документ 19", file: "documents/19.pdf" },
  { n: 20, title: "Документ 20", file: "documents/20.pdf" },
  { n: 21, title: "Документ 21", file: "documents/21.pdf" },
  { n: 22, title: "Документ 22", file: "documents/22.pdf" },
  { n: 23, title: "Документ 23", file: "documents/23.pdf" },
  { n: 24, title: "Документ 24", file: "documents/24.pdf" },
  { n: 25, title: "Документ 25", file: "documents/25.pdf" },
  { n: 26, title: "Документ 26", file: "documents/26.pdf" },
  { n: 27, title: "Документ 27", file: "documents/27.pdf" },
  { n: 28, title: "Документ 28", file: "documents/28.pdf" },
  { n: 29, title: "Документ 29", file: "documents/29.pdf" },
  { n: 30, title: "Документ 30", file: "documents/30.pdf" },
  { n: 31, title: "Документ 31", file: "documents/31.pdf" },
  { n: 32, title: "Документ 32", file: "documents/32.pdf" },
  { n: 33, title: "Документ 33", file: "documents/33.pdf" },
  { n: 34, title: "Документ 34", file: "documents/34.pdf" },
  { n: 35, title: "Документ 35", file: "documents/35.pdf" },
  { n: 36, title: "Документ 36", file: "documents/36.pdf" },
  { n: 37, title: "Документ 37", file: "documents/37.pdf" }
];
